# Site settings
title: La cuisine de Jiminy
email: panozpublishingteam@gmail.com
description: "Des recettes Fitness & Pâtisserie"
baseurl: "https://jaypanoz.github.io/cuisine"
language: "fr"
lang_direction: "ltr"
color: "#e60000"
twitter_username: JiminyPan
github_username:  JayPanoz

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true
  posts:
    permalink: /:collection/:title:output_ext

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  permalink: '/home-:num/'
  collection: 'recipes'
  per_page: 18
  sort_field: 'title'
  trail:
    before: 1
    after: 1

exclude: ['Gemfile.lock', 'Rakefile', 'README.md']

translation:
  en:
    recipes: "Recipes"
    components: "Components"
    ingredients: "Ingredients"
    directions: "Directions"
    category: "Category"
    nutritional_information: "Nutritional Information"
    component_based: 'This is a <strong class="accent">component-based recipe</strong>.'
    search: "Search"
    blog: "Blog"
    subscribe: "Subscribe"
    read_more: "Read More"
    yield: "Yield"
    prep: "Prep"
    cook: "Cook"
    totaltime: "Total"
    storage: "Storage"
    tip: "Tip"
    more: "Discover more"
    paginator_first: "First"
    paginator_previous: "Previous"
    paginator_next: "Next"
    paginator_last: "Last"
    browse_by: "Browse by:"
    collections: "Collections"
    collections_browse: "No recipes are marked as being part of a collection."
    courses: "Courses"
    course_browse: "No recipes are marked as being for a specific course."
    cuisines: "Cuisines"
    cuisine_browse: "No recipes are marked as being for a specific cuisine."
    diets: "Diets"
    diet_browse: "No recipes are marked as being for a specific diet."
    tags: "Tags"
    tag_browse: "No recipes have any tags yet."
  fr:
    recipes: "Recettes"
    components: "Préparations"
    ingredients: "Ingrédients"
    directions: "Instructions"
    category: "Catégorie"
    nutritional_information: "Informations nutritionnelles (théoriques)"
    component_based: 'Cette recette est composée <strong class="accent">d’une ou plusieurs préparations</strong>.'
    search: "Recherche"
    blog: "Blog"
    subscribe: "S’abonner"
    read_more: "Lire le billet"
    yield: Parts
    prep: "Prép."
    cook: "Cuisson"
    totaltime: "Total"
    storage: "Conservation"
    tip: "Astuce"
    more: "Découvrez plus"
    paginator_first: "Début"
    paginator_previous: "Précédent"
    paginator_next: "Suivant"
    paginator_last: "Fin"
    browse_by: "Naviguer par:"
    collections: "Collections"
    collections_browse: "Aucune recette n’a encore été ajoutée à une collection."
    courses: "Types de plat"
    course_browse: "Aucune recette n’a encore été taggée pour un type de plat."
    cuisines: "Types de cuisine"
    cuisine_browse: "Aucune recette n’a encore été taggée pour un type de cuisine."
    diets: "Régimes alimentaires"
    diet_browse: "Aucune recette n’a encore été taggée pour un type de régime alimentaire."
    tags: "Tags"
    tag_browse: "Aucune recette n’a encore été taggée."