# Site settings
title: La cuisine de Jiminy
email: panozpublishingteam@gmail.com
description: "Des recettes Fitness & Pâtisserie"
baseurl: "https://jaypanoz.github.io/cuisine"
language: "fr"
lang_direction: "ltr"
color: "#e60000"
twitter_username: JiminyPan
github_username:  JayPanoz

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

translation:
  en:
    components: "Components"
    ingredients: "Ingredients"
    directions: "Directions"
    category: "Category"
    nutritional_information: "Nutritional Information"
    component_based: 'This is a <strong class="blue">component-based recipe</strong>.'
    search: "Search"
    blog: "Blog"
    subscribe: "Subscribe"
    yield: "Yield"
    prep: "Prep"
    cook: "Cook"
    totaltime: "Total"
    storage: "Storage"
    browse_by: "Browse by:"
    courses: "Courses"
    course_browse: "No recipes are marked as being for a specific course."
    cuisines: "Cuisines"
    cuisine_browse: "No recipes are marked as being for a specific cuisine."
    diets: "Diets"
    diet_browse: "No recipes are marked as being for a specific diet."
    tags: "Tags"
    tag_browse: "No recipes have any tags yet."
  fr:
    components: "Préparations"
    ingredients: "Ingrédients"
    directions: "Instructions"
    category: "Catégorie"
    nutritional_information: "Informations nutritionnelles (théoriques)"
    component_based: 'Cette recette est composée <strong class="blue">d’une ou plusieurs préparations</strong>.'
    search: "Recherche"
    blog: "Blog"
    subscribe: "S’abonner"
    yield: Parts
    prep: "Prép."
    cook: "Cuisson"
    totaltime: "Total"
    storage: "Conservation"
    browse_by: "Naviguer par:"
    courses: "Type de plat"
    course_browse: "Aucune recette n’a encore été taggée pour un type de plat."
    cuisines: "Types de cuisine"
    cuisine_browse: "Aucune recette n’a encore été taggée pour un type de cuisine."
    diets: "Régimes alimentaires"
    diet_browse: "Aucune recette n’a encore été taggée pour un type de régime alimentaire."
    tags: "Tags"
    tag_browse: "Aucune recette n’a encore été taggée."