# Site settings
title: La cuisine de Jiminy
email: panozpublishingteam@gmail.com
description: "Des recettes Fitness & Pâtisserie"
baseurl: ""
language: "fr"
lang_direction: "ltr"
color: "#e60000"
twitter_username: JiminyPan
github_username:  JayPanoz

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

translation:
  en:
    components: "Components"
    ingredients: "Ingredients"
    directions: "Directions"
    category: "Category"
    nutritional_information: "Nutritional Information"
    component_based: 'This is a <strong class="blue">component-based recipe</strong>.'
    search: "Search"
    blog: "Blog"
    subscribe: "Subscribe"
  de:
    components: "Komponenten"
    ingredients: "Zutaten"
    directions: "Zubereitung"
    category: "Kategorie"
    nutritional_information: "Nährwertangaben"
    component_based: 'Dieses Rezept besteht aus <strong class="blue">mehreren Komponenten</strong>.'
    search: "Suche"
    blog: "Blog"
    subscribe: "Abonnieren"
  fr:
    components: "Préparations"
    ingredients: "Ingrédients"
    directions: "Instructions"
    category: "Catégorie"
    nutritional_information: "Informations nutritionnelles (théoriques)"
    component_based: 'Cette recette est <strong class="blue">composée de plusieurs préparations</strong>.'
    search: "Recherche"
    blog: "Blog"
    subscribe: "S’abonner"